# This job will only run for pull requests, specifically those created by Dependabot.
# This will auto-merge Dependabot PRs that are minor updates and if they pass all tests.

name: Auto Merge
permissions:
  pull-requests: write   # Needed to approve & merge PRs
  contents: write

on:
  pull_request:

jobs:
  auto-approve:
    name: Dependabot Auto Approve
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Approve Dependabot PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.MYTOKEN }}
          review-message: "dependabot PR auto-approved ✅"

  auto-merge:
    name: Dependabot Auto Merge
    needs: auto-approve   # ensure merge happens after approval
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.MYTOKEN }}
